services:
  soltip:
    platform: linux/amd64
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=production
      - PORT=4040
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data:/app/data 